name: CI (Xcode)

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  xcode_ventura:
    name: Xcode ${{ matrix.xcode }} (Xcode Project)
    runs-on: macos-13
    strategy:
      matrix:
        xcode: ["14.3.1"]
      fail-fast: false
    env:
      DEVELOPER_DIR: "/Applications/Xcode_${{ matrix.xcode }}.app"
    steps:
      - uses: actions/checkout@v5
      - run: ./test macos
      - run: ./test ios
      - run: ./test tvos
      - run: ./test watchos

  xcode_sonoma:
    name: Xcode ${{ matrix.xcode }} (Xcode Project)
    runs-on: macos-14
    strategy:
      matrix:
        xcode: ["15.4", "16.1"]
      fail-fast: false
    env:
      DEVELOPER_DIR: "/Applications/Xcode_${{ matrix.xcode }}.app"
    steps:
      - uses: actions/checkout@v5
      - run: ./test macos
      - run: ./test ios
      - run: ./test tvos
      - run: ./test watchos

  xcode_spm:
    name: Xcode ${{ matrix.xcode }} (Swift Package)
    runs-on: macos-14
    strategy:
      matrix:
        xcode: ["16.1"]
      fail-fast: false
    env:
      DEVELOPER_DIR: "/Applications/Xcode_${{ matrix.xcode }}.app"
    steps:
      - uses: actions/checkout@v5
      - run: ./test macos_xcodespm
      - run: ./test ios_xcodespm
      - run: ./test tvos_xcodespm
      - run: ./test watchos_xcodespm
