name: SwiftWasm

on:
  pull_request:
    paths:
      - .github/workflows/wasm.yml
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  test:
    name: Test SwiftWasm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: swiftwasm/swiftwasm-action@v5.8
